/*
 * Copyright (c) 2024-2026 Anatoly Gudkov and others.
 *
 * Licensed under the MIT License.
 * See the LICENSE file in the project root for details.
 */

rootProject.name = 'discas'

include 'discas-common'
include 'discas-node'
include 'discas-client'
include 'discas-agent'
include 'discas-admin'
include 'discas-example'
include 'discas-int-test'
include 'discas-performance'
include 'discas-all'
