/*
 * Copyright (c) 2024-2026 Anatoly Gudkov and others.
 *
 * Licensed under the MIT License.
 * See the LICENSE file in the project root for details.
 */

package io.github.green4j.discas.admin.runbook;

import io.github.green4j.discas.admin.runbook.ClusterPlan.ClientAuth;
import io.github.green4j.discas.common.identity.NodeId;

import java.net.InetSocketAddress;
import java.time.Instant;
import java.util.Arrays;
import java.util.List;
import java.util.Map;

/**
 * {@code RUN.md}: what an operator has to do with the folder {@code init} just built.
 *
 * <p>Written as a list of named sections rather than one long append, because that is what it is --
 * and because the order is an argument: what this is, what is in it, what you must not do, how to
 * start it, how clients get in, what they are allowed to touch, how to tell it worked, and how to
 * change any of it afterwards. A section added later goes in that order or it goes nowhere.
 *
 * <p>The runbook never invents a value. Everything variable comes from the {@link ClusterPlan}, and
 * where the plan cannot know something -- a TLS password -- it says so and names the environment
 * variable rather than leaving a bracket for somebody to fill in wrongly at three in the morning.
 */
public final class Runbook {

    /** The runbook's own file name inside the generated folder. */
    public static final String FILE_NAME = "RUN.md";

    /** The membership file written beside it, in the format {@code --members-file} reads. */
    public static final String MEMBERS_FILE_NAME = "members.conf";

    /** One part of the runbook. */
    @FunctionalInterface
    private interface Section {
        void write(Markdown md, ClusterPlan plan, long pairsPerMember);
    }

    private static final List<Section> SECTIONS = Arrays.asList(
            Runbook::overview,
            Runbook::folder,
            Runbook::rules,
            Runbook::bringItUp,
            Runbook::clientAccess,
            Runbook::authorization,
            Runbook::verify,
            Runbook::changingThingsLater);

    private Runbook() {
    }

    /** @param pairsPerMember what was actually seeded, so the runbook states what happened */
    public static String render(final ClusterPlan plan, final long pairsPerMember) {
        final Markdown md = new Markdown();
        for (final Section section : SECTIONS) {
            section.write(md, plan, pairsPerMember);
        }
        return md.toString();
    }

    /** The membership file's content -- generated here because the runbook is what explains it. */
    public static String membersFile(final Map<NodeId, InetSocketAddress> members) {
        final StringBuilder text = new StringBuilder();
        text.append("# discas membership, one line per member: node.<id>=<peer host:port>\n");
        for (final Map.Entry<NodeId, InetSocketAddress> member : members.entrySet()) {
            text.append("node.").append(member.getKey().value()).append('=')
                    .append(address(member.getValue())).append('\n');
        }
        return text.toString();
    }

    private static void overview(final Markdown md, final ClusterPlan plan, final long pairs) {
        md.h1("Starting cluster `" + plan.clusterId().value() + "`");
        md.p("Generated by `discas-admin init` at " + Instant.now() + ".");
        md.bullet("**Cluster id:** `" + plan.clusterId().value() + "` -- every member must be started "
                + "with exactly this, and no other cluster may use it.");
        md.bullet("**Members:** " + plan.members().size() + " (`" + ids(plan) + "`). This is `N`, and "
                + "it is frozen: a discas cluster cannot be resized while it runs.");
        md.bullet("**Seeded from:** " + (plan.dump() == null
                ? "nothing -- the cluster starts empty"
                : "`" + plan.dump() + "`, " + pairs + " pairs in every member") + ".");
        md.bullet("**Client access:** `" + plan.clientAuth().cliName() + "` -- "
                + plan.clientAuth().summary() + ".");
    }

    private static void folder(final Markdown md, final ClusterPlan plan, final long pairs) {
        md.h2("What is in this folder");
        final StringBuilder listing = new StringBuilder();
        listing.append(pad(FILE_NAME)).append("this file\n");
        listing.append(pad(MEMBERS_FILE_NAME))
                .append("the membership, in the format --members-file reads\n");
        for (final NodeId id : plan.members().keySet()) {
            listing.append(pad(id.value() + "/"))
                    .append("data directory for member ").append(id.value()).append('\n');
        }
        md.code("", listing.toString());
        md.p("Each member directory holds that member's WAL"
                + (pairs == 0 ? " (empty -- nothing was seeded)" : "")
                + " and an `incarnation` file: the marker that says this storage has been "
                + "initialised. **The markers are different in every directory, and that is the "
                + "point.**");
    }

    private static void rules(final Markdown md, final ClusterPlan plan, final long pairs) {
        md.h2("Rules that are not negotiable");
        final NodeId first = plan.members().keySet().iterator().next();
        md.step(1, "**One directory, one member, forever.** Give `" + first.value() + "/` to the host "
                + "that will run member `" + first.value() + "`, and never to another. Two members "
                + "sharing a directory's history are two acceptors claiming one identity.");
        md.step(2, "**Do not copy a directory after a member has started on it.** A copy is state the "
                + "original has already moved past; brought back, it is not behind, it is "
                + "authoritatively wrong. Take a fresh dump and run `init` again instead.");
        md.step(3, "**Do not start these against an existing cluster.** They are a *new* cluster: no "
                + "member of theirs has promised anything to anyone, and every pair sits at one low "
                + "ballot. Point them only at each other.");
        md.step(4, "**Start every member before sending traffic.** A majority is enough to answer, but "
                + "a member left unstarted is a member whose absence you will discover during the "
                + "next failure rather than now.");
    }

    private static void bringItUp(final Markdown md, final ClusterPlan plan, final long pairs) {
        md.h2("Bringing it up");
        md.p("For each member: copy its directory and the membership file to that host, then start "
                + "the node.");
        for (final Map.Entry<NodeId, InetSocketAddress> member : plan.members().entrySet()) {
            final NodeId id = member.getKey();
            final String host = host(member.getValue());
            md.h3("Member `" + id.value() + "` -- " + address(member.getValue()));
            md.code("sh", copyCommands(plan, id, host) + "\n" + startCommand(plan, id, member.getValue()));
        }
        if (plan.peerTls() || plan.clientTls()) {
            md.p("**Passwords are not in this file, and must not be.** Pass them as `DISCAS_*` "
                    + "environment variables (`DISCAS_TLS_KEYSTORE_PASSWORD`, "
                    + "`DISCAS_TLS_TRUSTSTORE_PASSWORD`, and the `DISCAS_CLIENT_TLS_*` pair for the "
                    + "client port); every node option accepts one.");
        }
    }

    private static void clientAccess(final Markdown md, final ClusterPlan plan, final long pairs) {
        md.h2("How clients get in");
        md.p("This cluster was planned with `--client-auth " + plan.clientAuth().cliName() + "`: "
                + plan.clientAuth().summary() + ".");
        switch (plan.clientAuth()) {
            case ALLOWALL:
                md.p("**Nothing authenticates.** A client's claimed id is believed, so the client "
                        + "port must not be reachable from anywhere you would not trust with every "
                        + "key. This is the right setting for a private network and the wrong one "
                        + "for everything else.");
                break;
            case TOKEN:
                md.p("Create `" + plan.tokenFile() + "` on every member before starting it -- a node "
                        + "with token auth and no token file refuses every client. It is java "
                        + "properties, one line per client, re-read whenever you ask a node to "
                        + "reload. The file holds a hash rather than the token, so mint each line "
                        + "rather than writing it:");
                md.code("sh", "discas-admin token --client-id web-1 --ttl-days 90 >> "
                        + plan.tokenFile() + "\n");
                md.p("The record goes to standard output and the token itself to standard error, so "
                        + "the redirect appends the right line while the secret still reaches your "
                        + "terminal. It is shown once and stored nowhere.");
                md.code("", "client.web-1 = pbkdf2$210000$<saltB64>$<hashB64>$<notAfterEpochMs>\n"
                        + "client.reporter = pbkdf2$...$<notAfter> ; pbkdf2$...$<notAfter>\n");
                md.p("Two records on one line is how a token is rotated without an outage: the old "
                        + "one keeps working until its `notAfter`. The directory form (one "
                        + "`<clientId>.token` file per client) takes the same records. Either way "
                        + "the edit reaches a node when you `POST /reload` on it -- see "
                        + "\"Changing things later\" below.");
                break;
            case MTLS:
                md.p("Clients present a certificate and its CN is the client id -- the id in the "
                        + "handshake is ignored, so a client cannot claim to be another. The client "
                        + "port therefore runs TLS (that is not a separate choice), and every "
                        + "member needs the CA trust store that signs client certificates. Paths "
                        + "are in the start commands above; passwords go in the environment.");
                break;
            default:
                break;
        }
    }

    private static void authorization(final Markdown md, final ClusterPlan plan, final long pairs) {
        md.h2("What clients may touch");
        if (plan.aclFile() == null) {
            md.p("**No ACL file.** Every client that authenticates may read and write every key. "
                    + "That is a deliberate setting and a defensible one for a single-application "
                    + "cluster; it is indefensible for a shared one. Add `--client-acl-file` to the "
                    + "start commands when a second application arrives.");
            return;
        }
        md.p("Create `" + plan.aclFile() + "` on every member. It is java properties, one line per "
                + "client, re-read on request, and grants are `<keyPrefix>:<ops>`:");
        md.code("", "acl.web-1 = app/:GPCD ; session/:GPCDS\n"
                + "acl.reporter = report/:GS\n");
        md.p("The ops are letters: `G` get, `P` put, `C` compare-and-set, `D` delete, `S` scan. A "
                + "client with no line in the file may do nothing, which is the point of having the "
                + "file at all.");
    }

    private static void verify(final Markdown md, final ClusterPlan plan, final long pairs) {
        md.h2("Checking it worked");
        md.p("Once every member is up, dump the new cluster and count what comes back. The "
                + "addresses here are the **client** port, not the peer port: a dump is a client, "
                + "and it talks where clients talk.");
        md.code("sh", "discas-admin dump --nodes " + clientEndpoints(plan)
                + " \\\n  --out /tmp/check.dump" + (plan.clientAuth() == ClientAuth.TOKEN
                ? " \\\n  --client-id <a client in your token file> --token <its token>" : "") + "\n");
        md.p(pairs == 0
                ? "The cluster was seeded empty, so the dump should carry no pairs. What it proves "
                + "is the part that matters here: every member answered."
                : "It should carry " + pairs + " pairs -- the number seeded into each member. Fewer "
                + "means a member was started on the wrong directory, or traffic reached the "
                + "cluster before every member was up.");
    }

    private static void changingThingsLater(final Markdown md, final ClusterPlan plan,
                                           final long pairs) {
        md.h2("Changing things later");
        md.p("The membership file"
                + (plan.clientAuth() == ClientAuth.TOKEN ? ", the token file" : "")
                + (plan.aclFile() == null ? "" : ", the ACL")
                + (plan.peerTls() || plan.clientTls() ? " and the key and trust stores" : "")
                + " are read when you ask a node to read them, and at no other time. Edit the file "
                + "on the host -- in place, with whatever editor you like, taking as long as you "
                + "like -- and then put it in force:");
        md.code("sh", "curl -X POST http://127.0.0.1:9600/reload\n");
        md.p("Two things follow from the reload being one call rather than one per file. It applies "
                + "**all** of them or **none**: if any file does not parse, the node keeps running "
                + "on exactly what it was running on, which is what makes it safe to replace a "
                + "certificate and its key together. And it answers -- a JSON body naming each "
                + "file and what became of it, `applied`, `unchanged` or `failed` with the reason "
                + "-- so \"did my edit take effect\" is a question with an answer rather than a "
                + "guess. A refused reload is a `400`.");
        md.p("Do it on every member: each node reads its own copy of these files, and a change "
                + "applied to some members and not others is the state to avoid. The endpoint is on "
                + "the observability port, which is loopback by default -- run the `curl` on the "
                + "host, or set `--observability-bind` to somewhere your tooling can reach and "
                + "treat that port as administrative.");
        md.p("What cannot be changed this way: `N` (the cluster size is frozen), a node's id, and "
                + "its data directory. Those are the start command, not the files.");
    }

    private static String copyCommands(final ClusterPlan plan, final NodeId id, final String host) {
        final StringBuilder sh = new StringBuilder();
        sh.append("scp -r ").append(id.value()).append(' ').append(host).append(':')
                .append(plan.dataDirectoryOf(id)).append('\n');
        sh.append("scp ").append(MEMBERS_FILE_NAME).append(' ').append(host).append(':')
                .append(plan.configFile(MEMBERS_FILE_NAME)).append('\n');
        return sh.toString();
    }

    private static String startCommand(final ClusterPlan plan,
                                       final NodeId id,
                                       final InetSocketAddress peer) {
        final StringBuilder sh = new StringBuilder("discas-node \\\n");
        sh.append("  --node-id ").append(id.value()).append(" \\\n");
        sh.append("  --cluster-id ").append(plan.clusterId().value()).append(" \\\n");
        sh.append("  --members-file ").append(plan.configFile(MEMBERS_FILE_NAME)).append(" \\\n");
        sh.append("  --peer-bind ").append(address(peer)).append(" \\\n");
        sh.append("  --client-bind ").append(host(peer)).append(':').append(plan.clientPort())
                .append(" \\\n");
        sh.append("  --wal-dir ").append(plan.dataDirectoryOf(id));

        if (plan.peerTls()) {
            sh.append(" \\\n  --tls");
            sh.append(" \\\n  --tls-keystore ").append(plan.configFile("peer-keystore.p12"));
            sh.append(" \\\n  --tls-truststore ").append(plan.configFile("peer-truststore.p12"));
        }
        if (plan.clientAuth() != ClientAuth.ALLOWALL) {
            sh.append(" \\\n  --client-auth ").append(plan.clientAuth().cliName());
        }
        if (plan.clientAuth() == ClientAuth.TOKEN) {
            sh.append(" \\\n  --client-token-file ").append(plan.tokenFile());
        }
        if (plan.clientTls()) {
            sh.append(" \\\n  --client-tls");
            sh.append(" \\\n  --client-tls-keystore ").append(plan.configFile("client-keystore.p12"));
        }
        if (plan.clientAuth() == ClientAuth.MTLS) {
            sh.append(" \\\n  --client-tls-truststore ")
                    .append(plan.configFile("client-truststore.p12"));
        }
        if (plan.aclFile() != null) {
            sh.append(" \\\n  --client-acl-file ").append(plan.aclFile());
        }
        return sh.append('\n').toString();
    }

    private static String clientEndpoints(final ClusterPlan plan) {
        final StringBuilder joined = new StringBuilder();
        for (final Map.Entry<NodeId, InetSocketAddress> member : plan.members().entrySet()) {
            if (joined.length() > 0) {
                joined.append(',');
            }
            joined.append(member.getKey().value()).append('=')
                    .append(host(member.getValue())).append(':').append(plan.clientPort());
        }
        return joined.toString();
    }

    private static String ids(final ClusterPlan plan) {
        final StringBuilder joined = new StringBuilder();
        for (final NodeId id : plan.members().keySet()) {
            joined.append(joined.length() == 0 ? "" : ", ").append(id.value());
        }
        return joined.toString();
    }

    private static String address(final InetSocketAddress address) {
        return address.getHostString() + ":" + address.getPort();
    }

    private static String host(final InetSocketAddress address) {
        return address.getHostString();
    }

    /** Left-aligns a name in the folder listing, so the descriptions line up. */
    private static String pad(final String name) {
        final StringBuilder padded = new StringBuilder(name);
        while (padded.length() < 16) {
            padded.append(' ');
        }
        return padded.toString();
    }
}
